# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 23:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('location', models.CharField(max_length=100)),
                ('fee', models.FloatField()),
                ('camera_type', models.CharField(choices=[('NK', 'Nikon'), ('OL', 'Olympus'), ('GP', 'Go-Pro')], default='NIKON', max_length=2)),
                ('services', models.CharField(choices=[('WD', 'Wedding'), ('GD', 'Graduation'), ('SP', 'Active/Sports')], default='WEDDING', max_length=2)),
                ('bio', models.TextField()),
                ('phone', models.CharField(max_length=100)),
                ('photo_styles', models.CharField(choices=[('BW', 'Black and White'), ('CL', 'Color')], default='BW', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
