# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera_type',
            field=models.CharField(choices=[('NK', 'Nikon'), ('OL', 'Olympus'), ('GP', 'Go-Pro')], default='NK', max_length=2),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='services',
            field=models.CharField(choices=[('WD', 'Wedding'), ('GD', 'Graduation'), ('SP', 'Active/Sports')], default='WD', max_length=2),
        ),
    ]
