# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='photo',
            new_name='photos',
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
