# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20171130_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
